name: montecarlo-env
channels:
    - conda-forge
    - bioconda
    - nodefaults
dependencies:
    - python
    - numpy
    - pylint
    - pycodestyle
    - pydocstyle
    - networkx
    - matplotlib
